In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Bibliotecas

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from sklearn.metrics import mean_squared_log_error

import xgboost as xgb

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

import warnings; warnings.simplefilter('ignore')

# DataFrame Prepared

In [4]:
df_uni =pd.read_csv('/content/drive/MyDrive/tcc - maurício/df_final.csv')

In [5]:
df_uni.head()

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Venta_uni_hoy,Venta_hoy,Dev_uni_proxima,Dev_proxima,Demanda_uni_equil
0,4,1473,4,4803,17401,32303,12,71.16,0,0.0,12
1,4,1473,4,4803,17401,34433,12,96.00,0,0.0,12
2,4,1473,4,4803,17401,43038,7,83.44,0,0.0,7
3,4,1473,4,4803,17401,43039,10,93.80,0,0.0,10
4,4,1473,4,4803,17401,43040,5,34.10,0,0.0,5

In [6]:
train = df_uni[df_uni['test']==0]
predict = df_uni[df_uni['test']==1]

KeyError: ignored

In [ ]:
y = train['Demanda_uni_equil']
X = train[[ 'Agencia_ID','Canal_ID','Cliente_ID','Producto_ID','Ruta_SAK','mediaClientProd','quantClientProd', 'mediaProd', 'quantProd', 'mediaClient','quantClient']]

In [ ]:
print(X.shape, y.shape)

(10408713, 11) (10408713,)

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(X_train.shape, X_test.shape, y_train.shape , y_test.shape)

(8326970, 11) (2081743, 11) (8326970,) (2081743,)

# DecisionTreeRegressor

In [ ]:
dt_regressor = DecisionTreeRegressor()

In [ ]:
dt_regressor.fit(X_train, y_train)

In [ ]:
y_pred_dt = dt_regressor.predict(X_test)

## Root Mean Squared Logaritmic Error (RMSLE) Decision Tree Regressor

In [ ]:
rmsle_dt = np.sqrt(mean_squared_log_error(y_test, y_pred_dt))

In [ ]:
rmsle_dt

# Random forest

In [ ]:
RF_regression = RandomForestRegressor()

In [ ]:
RF_regression.fit(X_train,y_train)

In [ ]:
y_pred_rf = RF_regression.predict(X_test)

##  Root Mean Squared Logaritmic Error (RMSLE) Random Forest

In [ ]:
rmsle_rf = np.sqrt(mean_squared_log_error(y_test, y_pred_rf))

In [ ]:
rmsle_rf

# XGboost

In [ ]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear',max_depth = 12, alpha = 10, n_estimators = 2 , subsample=0.85 )

In [ ]:
xg_reg.fit(X_train,y_train)

[23:58:18] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:58:18] WARNING: /workspace/src/learner.cc:686: Tree method is automatically selected to be 'approx' for faster speed. To use old behavior (exact greedy algorithm on single machine), set tree_method to 'exact'.

XGBRegressor(alpha=10, max_depth=12, n_estimators=2, subsample=0.85)

In [ ]:
y_pred_xgb = xg_reg.predict(X_test)

In [ ]:
y_pred_xgb

array([0.70834553, 0.58380276, 0.8811786 , ..., 1.00523   , 0.7752168 ,
       0.6065049 ], dtype=float32)

In [ ]:
rmsle_xgb = np.sqrt(mean_squared_log_error(y_test, y_pred_xgb))

In [ ]:
rmsle_xgb

0.45464506524124776

# Submission XGboost Regressor

In [ ]:
predict.drop('Unnamed: 0', axis=1 ,inplace=True)

In [ ]:
predict.head()

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Demanda_uni_equil,id,test,mediaClientProd,quantClientProd,mediaProd,quantProd,mediaClient,quantClient
2,10,2655,2,4189,26,31518,0.0,1569352,1,NaN,NaN,13.333333,129.0,27.091603,131.0
3,11,2655,2,4189,26,31520,0.0,4728674,1,NaN,NaN,27.497359,1136.0,27.091603,131.0
7,11,2061,2,7212,26,34206,0.0,1547831,1,74.000000,4.0,25.740823,64261.0,27.091603,131.0
9,10,2061,2,7212,26,34210,0.0,6667200,1,36.000000,4.0,119.835431,8659.0,27.091603,131.0
14,10,2061,2,7212,26,34785,0.0,1592616,1,18.333333,3.0,85.906958,8609.0,27.091603,131.0

In [ ]:
predict[predict['Semana']==10]

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Demanda_uni_equil,id,test,mediaClientProd,quantClientProd,mediaProd,quantProd,mediaClient,quantClient
2,10,2655,2,4189,26,31518,0.0,1569352,1,NaN,NaN,13.333333,129.0,27.091603,131.0
9,10,2061,2,7212,26,34210,0.0,6667200,1,36.000000,4.0,119.835431,8659.0,27.091603,131.0
14,10,2061,2,7212,26,34785,0.0,1592616,1,18.333333,3.0,85.906958,8609.0,27.091603,131.0
17,10,2061,2,7212,26,34786,0.0,3909690,1,64.000000,4.0,159.838933,10567.0,27.091603,131.0
22,10,2061,2,7212,26,35142,0.0,3659672,1,38.250000,4.0,50.066907,8594.0,27.091603,131.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17407949,10,22362,1,900,2015152015,1230,0.0,608029,1,NaN,NaN,2.079283,371654.0,39.789474,19.0
17407951,10,22362,1,900,2015152015,1232,0.0,5838266,1,NaN,NaN,2.873842,814164.0,39.789474,19.0
17407954,10,22362,1,900,2015152015,1238,0.0,2542921,1,NaN,NaN,3.107030,660831.0,39.789474,19.0
17407956,10,22362,1,900,2015152015,1250,0.0,3223836,1,16.000000,1.0,6.464144,1062639.0,39.789474,19.0
17407962,10,22362,1,900,2015152015,4280,0.0,1066859,1,NaN,NaN,7.229038,223509.0,39.789474,19.0

In [ ]:
X_semana_10 =  predict[predict['Semana']==10][['Agencia_ID','Canal_ID','Cliente_ID','Producto_ID','Ruta_SAK','mediaClientProd','quantClientProd', 'mediaProd', 'quantProd', 'mediaClient','quantClient']]
X_semana_11 =  predict[predict['Semana']==11][['Agencia_ID','Canal_ID','Cliente_ID','Producto_ID','Ruta_SAK','mediaClientProd','quantClientProd', 'mediaProd', 'quantProd', 'mediaClient','quantClient']]

In [ ]:
X_semana_10.head()

,Agencia_ID,Canal_ID,Cliente_ID,Producto_ID,Ruta_SAK,mediaClientProd,quantClientProd,mediaProd,quantProd,mediaClient,quantClient
2,2655,2,26,31518,4189,NaN,NaN,13.333333,129.0,27.091603,131.0
9,2061,2,26,34210,7212,36.000000,4.0,119.835431,8659.0,27.091603,131.0
14,2061,2,26,34785,7212,18.333333,3.0,85.906958,8609.0,27.091603,131.0
17,2061,2,26,34786,7212,64.000000,4.0,159.838933,10567.0,27.091603,131.0
22,2061,2,26,35142,7212,38.250000,4.0,50.066907,8594.0,27.091603,131.0

In [ ]:
y_semana_10 = xg_reg.predict(X_semana_10)
y_semana_11 = xg_reg.predict(X_semana_11)

In [ ]:
submission_10 = pd.DataFrame({'id':predict[predict['Semana']==10]['id'], 'Demanda_uni_equil': y_semana_10})
submission_11 = pd.DataFrame({'id':predict[predict['Semana']==11]['id'], 'Demanda_uni_equil': y_semana_11})

In [ ]:
submit = pd.concat([submission_10[['id','Demanda_uni_equil']],submission_11[['id','Demanda_uni_equil']]], axis=0, copy=True)

In [ ]:
submit

               id  Demanda_uni_equil
2         1569352           0.942792
9         6667200           1.060648
14        1592616           0.939602
17        3909690           1.232842
22        3659672           1.060648
...           ...                ...
17407943  2306934           0.612185
17407944  4894078           0.612185
17407945  3413579           0.743370
17407952  6093628           0.574063
17407959  1889878           0.932603

[6999251 rows x 2 columns]

In [ ]:
submit.to_csv('/content/drive/MyDrive/tcc - maurício/prediction_xgb', index=False)